name: "migrate-values"
version: "0.0.1"
usage: "schema migration for Helm values"
description: "Tool for ensuring user-supplied chart values are kept up to date with the chart's values schema."
command: "$HELM_PLUGIN_DIR/bin/migrate-values"
hooks:
  install: "make build"